testing

In [1]:
print("Support-Sense ML notebook is working!")

Support-Sense ML notebook is working!

In [2]:
import pandas as pd

twitter_path = r"D:\damn\raw\twitter\twcs.csv"

twitter_df = pd.read_csv(twitter_path)

print("Rows:", len(twitter_df))
print("Columns:", list(twitter_df.columns))

Rows: 2811774
Columns: ['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

In [3]:
twitter_df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [4]:
bitext_path = r"D:\damn\raw\hugging-face\Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv"

bitext_df = pd.read_csv(bitext_path)

print("Rows:", len(bitext_df))
print("Columns:", list(bitext_df.columns))

Rows: 26872
Columns: ['flags', 'instruction', 'category', 'intent', 'response']

In [5]:
bitext_df.head()

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [6]:
bitext_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26872 entries, 0 to 26871
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   flags        26872 non-null  str
 1   instruction  26872 non-null  str
 2   category     26872 non-null  str
 3   intent       26872 non-null  str
 4   response     26872 non-null  str
dtypes: str(5)
memory usage: 19.1 MB

In [7]:
twitter_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2811774 entries, 0 to 2811773
Data columns (total 7 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tweet_id                 int64
 1   author_id                str
 2   inbound                  bool
 3   created_at               str
 4   text                     str
 5   response_tweet_id        str
 6   in_response_to_tweet_id  float64
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 557.8 MB

In [8]:
twitter_df.isnull().sum()

tweet_id                         0
author_id                        0
inbound                          0
created_at                       0
text                             0
response_tweet_id          1040629
in_response_to_tweet_id     794335
dtype: int64

In [9]:
twitter_df["inbound"].value_counts()

inbound
True     1537843
False    1273931
Name: count, dtype: int64

In [10]:
twitter_df["author_id"].nunique()

702777

In [11]:
twitter_df.groupby("inbound")["author_id"].nunique()

inbound
False       108
True     702669
Name: author_id, dtype: int64

In [12]:
twitter_df.loc[twitter_df["inbound"] == False, "author_id"].value_counts().head(20)

author_id
AmazonHelp         169840
AppleSupport       106860
Uber_Support        56270
SpotifyCares        43265
Delta               42253
Tesco               38573
AmericanAir         36764
TMobileHelp         34317
comcastcares        33031
British_Airways     29361
SouthwestAir        28977
VirginTrains        27817
Ask_Spectrum        25860
XboxSupport         24557
sprintcare          22381
hulu_support        21872
sainsburys          19466
GWRHelp             19364
AskPlayStation      19098
ChipotleTweets      18749
Name: count, dtype: int64

In [13]:
twitter_df["created_at"].min(), twitter_df["created_at"].max()

('Fri Apr 01 17:37:48 +0000 2016', 'Wed Sep 28 18:06:15 +0000 2016')

In [14]:
bitext_df["category"].value_counts()

category
ACCOUNT         5986
ORDER           3988
REFUND          2992
INVOICE         1999
CONTACT         1999
PAYMENT         1998
FEEDBACK        1997
DELIVERY        1994
SHIPPING        1970
SUBSCRIPTION     999
CANCEL           950
Name: count, dtype: int64

In [15]:
bitext_df["intent"].value_counts()

intent
check_invoice               1000
complaint                   1000
contact_customer_service    1000
edit_account                1000
switch_account              1000
check_payment_methods        999
contact_human_agent          999
delivery_period              999
get_invoice                  999
newsletter_subscription      999
payment_issue                999
registration_problems        999
cancel_order                 998
place_order                  998
track_refund                 998
change_order                 997
check_refund_policy          997
create_account               997
get_refund                   997
review                       997
set_up_shipping_address      997
delete_account               995
delivery_options             995
recover_password             995
track_order                  995
change_shipping_address      973
check_cancellation_fee       950
Name: count, dtype: int64